'use strict';

/**
 * Integration test: full CLI flow with a real local
 * "remote" git repo. Tests:
 *   - --init cloning
 *   - .env generation
 *   - shared secret resolution
 *   - project cleanup (--clean)
 *   - deleted project resilience
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');

const SANDBOX = path.join(os.tmpdir(), 'secenv-integ-' + Date.now());
const MOCK_HOME = path.join(SANDBOX, 'home');
const REMOTE_REPO = path.join(SANDBOX, 'remote-git');
const PROJECT_DIR = path.join(SANDBOX, 'test-project');

const CLI_PATH = path.join(__dirname, '..', 'bin', 'secenv.js');

test.before(() => {
  fs.mkdirSync(MOCK_HOME, { recursive: true });
  fs.mkdirSync(REMOTE_REPO, { recursive: true });
  fs.mkdirSync(PROJECT_DIR, { recursive: true });

  process.env.USERPROFILE = MOCK_HOME;
  process.env.HOME = MOCK_HOME;

  // Use a stable branch name and disable GPG signing for CI
  process.env.GIT_DEFAULT_BRANCH = 'main';

  // Initialize bare "remote" repo
  execSync('git init --bare --initial-branch=main', { cwd: REMOTE_REPO });
  execSync('git config --global user.email "test@test.com"',
    { env: { ...process.env, HOME: MOCK_HOME } });
  execSync('git config --global user.name "Test"',
    { env: { ...process.env, HOME: MOCK_HOME } });
  execSync('git config --global init.defaultBranch main',
    { env: { ...process.env, HOME: MOCK_HOME } });
  execSync('git config --global commit.gpgsign false',
    { env: { ...process.env, HOME: MOCK_HOME } });
  execSync('git config --global tag.gpgsign false',
    { env: { ...process.env, HOME: MOCK_HOME } });

  // Initial commit with secrets
  const tempClone = path.join(SANDBOX, 'temp-clone');
  execSync(`git clone "${REMOTE_REPO}" "${tempClone}"`);
  execSync('git checkout -b main', { cwd: tempClone });
  const initial = {
    shared: {
      SHARED_KEY: 'shared-value-123',
      API_TOKEN: 'shared-api-token',
    },
    projects: {
      'test-project': {
        DATABASE_URL: 'postgresql://localhost/db',
        API_TOKEN: 'shared.SHARED_KEY',
      },
    },
  };
  fs.writeFileSync(
    path.join(tempClone, 'secrets.json'),
    JSON.stringify(initial, null, 2)
  );
  execSync('git add secrets.json', { cwd: tempClone });
  execSync('git commit -m initial', { cwd: tempClone });
  execSync('git push -u origin main', { cwd: tempClone });

  // Set up test project
  fs.writeFileSync(
    path.join(PROJECT_DIR, '.env.example'),
    'DATABASE_URL=\nAPI_TOKEN=\n'
  );
  execSync('git init --initial-branch=main', { cwd: PROJECT_DIR });
  execSync(
    'git remote add origin https://github.com/chirag127/test-project.git',
    { cwd: PROJECT_DIR }
  );
});

test.after(() => {
  fs.rmSync(SANDBOX, { recursive: true, force: true });
});

test('integration: --help works', () => {
  const out = execSync(`node "${CLI_PATH}" --help`, {
    cwd: PROJECT_DIR,
    encoding: 'utf-8',
  });
  // secenv prints help to stderr
  const result = execSync(`node "${CLI_PATH}" --help 2>&1`, {
    cwd: PROJECT_DIR,
    encoding: 'utf-8',
  });
  assert.ok(result.includes('Centralized secrets manager'));
  assert.ok(result.includes('--init'));
});

test('integration: --version works', () => {
  const result = execSync(`node "${CLI_PATH}" --version 2>&1`, {
    cwd: PROJECT_DIR,
    encoding: 'utf-8',
  });
  assert.match(result.trim(), /^\d+\.\d+\.\d+$/);
});

test('integration: --init clones central repo', () => {
  execSync(`node "${CLI_PATH}" --init "${REMOTE_REPO}"`, {
    cwd: PROJECT_DIR,
    stdio: 'pipe',
  });
  const clonedDir = path.join(MOCK_HOME, '.secenv', 'secrets');
  assert.ok(
    fs.existsSync(path.join(clonedDir, 'secrets.json')),
    'secrets.json should exist after --init'
  );
});

test('integration: generates .env with shared resolution', () => {
  const envPath = path.join(PROJECT_DIR, '.env');
  if (fs.existsSync(envPath)) fs.unlinkSync(envPath);

  execSync(`node "${CLI_PATH}"`, {
    cwd: PROJECT_DIR,
    stdio: 'pipe',
  });

  assert.ok(fs.existsSync(envPath), '.env should be generated');
  const content = fs.readFileSync(envPath, 'utf-8');
  assert.ok(
    content.includes('DATABASE_URL=postgresql://localhost/db'),
    'direct value should be resolved'
  );
  assert.ok(
    content.includes('API_TOKEN=shared-value-123'),
    'shared reference should be resolved'
  );
  assert.ok(
    content.includes('Generated by secenv'),
    'should have header'
  );
});

test('integration: --list shows projects and shared keys', () => {
  const result = execSync(`node "${CLI_PATH}" --list 2>&1`, {
    cwd: PROJECT_DIR,
    encoding: 'utf-8',
  });
  assert.ok(result.includes('test-project'));
  assert.ok(result.includes('SHARED_KEY'));
  assert.ok(result.includes('API_TOKEN'));
});

test('integration: --clean handles deleted projects', () => {
  // Add a "stale" project to secrets.json
  const secretsPath = path.join(
    MOCK_HOME, '.secenv', 'secrets', 'secrets.json'
  );
  const cfg = JSON.parse(fs.readFileSync(secretsPath, 'utf-8'));
  cfg.projects['deleted-project'] = { K: 'v' };
  cfg.projects['another-deleted'] = { X: 'y' };
  fs.writeFileSync(secretsPath, JSON.stringify(cfg, null, 2));

  // First verify --clean dry-run (no --yes) detects them
  const dry = execSync(
    `node "${CLI_PATH}" --clean "${SANDBOX}" 2>&1 || true`,
    { cwd: PROJECT_DIR, encoding: 'utf-8' }
  );
  // Without --yes, stdin is a pipe so answer is empty
  // (readline returns empty string on EOF), which means
  // the prompt defaults to "no" (anything other than y/yes).
  const cfg2 = JSON.parse(
    fs.readFileSync(secretsPath, 'utf-8')
  );
  assert.ok(
    cfg2.projects['deleted-project'],
    'should still exist without --yes'
  );

  // Now run with --yes
  execSync(
    `node "${CLI_PATH}" --clean "${SANDBOX}" --yes 2>&1`,
    { cwd: PROJECT_DIR, encoding: 'utf-8' }
  );

  const cfg3 = JSON.parse(
    fs.readFileSync(secretsPath, 'utf-8')
  );
  assert.ok(
    !cfg3.projects['deleted-project'],
    'deleted-project should be removed'
  );
  assert.ok(
    !cfg3.projects['another-deleted'],
    'another-deleted should be removed'
  );
  assert.ok(
    cfg3.projects['test-project'],
    'test-project should remain (directory exists)'
  );
});

test('integration: --delete removes specific project', () => {
  // Add a project to delete
  const secretsPath = path.join(
    MOCK_HOME, '.secenv', 'secrets', 'secrets.json'
  );
  const cfg = JSON.parse(fs.readFileSync(secretsPath, 'utf-8'));
  cfg.projects['to-delete'] = { X: 'y' };
  fs.writeFileSync(secretsPath, JSON.stringify(cfg, null, 2));

  execSync(`node "${CLI_PATH}" --delete to-delete`, {
    cwd: PROJECT_DIR,
    stdio: 'pipe',
  });

  const cfg2 = JSON.parse(
    fs.readFileSync(secretsPath, 'utf-8')
  );
  assert.ok(
    !cfg2.projects['to-delete'],
    'to-delete should be gone'
  );
});

test('integration: --remove deletes shared key', () => {
  const secretsPath = path.join(
    MOCK_HOME, '.secenv', 'secrets', 'secrets.json'
  );
  const cfg = JSON.parse(fs.readFileSync(secretsPath, 'utf-8'));
  cfg.shared.TEMP_KEY = 'temp';
  fs.writeFileSync(secretsPath, JSON.stringify(cfg, null, 2));

  execSync(`node "${CLI_PATH}" --remove TEMP_KEY`, {
    cwd: PROJECT_DIR,
    stdio: 'pipe',
  });

  const cfg2 = JSON.parse(
    fs.readFileSync(secretsPath, 'utf-8')
  );
  assert.ok(
    !('TEMP_KEY' in cfg2.shared),
    'TEMP_KEY should be gone'
  );
});

test('integration: re-running regenerates .env', () => {
  // Modify secrets and verify next run picks it up
  const secretsPath = path.join(
    MOCK_HOME, '.secenv', 'secrets', 'secrets.json'
  );
  const cfg = JSON.parse(fs.readFileSync(secretsPath, 'utf-8'));
  cfg.shared.SHARED_KEY = 'updated-value-456';
  fs.writeFileSync(secretsPath, JSON.stringify(cfg, null, 2));

  // Commit + push from local clone
  execSync('git add secrets.json', {
    cwd: path.join(MOCK_HOME, '.secenv', 'secrets'),
  });
  execSync('git commit -m update', {
    cwd: path.join(MOCK_HOME, '.secenv', 'secrets'),
  });
  execSync('git push origin main', {
    cwd: path.join(MOCK_HOME, '.secenv', 'secrets'),
  });

  // Re-run
  execSync(`node "${CLI_PATH}"`, {
    cwd: PROJECT_DIR,
    stdio: 'pipe',
  });

  const content = fs.readFileSync(
    path.join(PROJECT_DIR, '.env'), 'utf-8'
  );
  assert.ok(
    content.includes('API_TOKEN=updated-value-456'),
    'should pick up updated value'
  );
});
