'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Write resolved env vars to a .env file.
 *
 * @param {Object<string,string>} envVars - Key-value pairs.
 * @param {string} [dir] - Directory to write to.
 * @returns {string} Absolute path to the written file.
 */
function writeEnvFile(envVars, dir) {
  const targetDir = dir || process.cwd();
  const filePath = path.join(targetDir, '.env');

  let content =
    '# Generated by secenv — DO NOT COMMIT\n';
  content +=
    `# Last updated: ${new Date().toISOString()}\n\n`;

  for (const [key, val] of Object.entries(envVars)) {
    const safeVal = needsQuoting(val)
      ? `"${escapeQuotes(val)}"`
      : val;
    content += `${key}=${safeVal}\n`;
  }

  fs.writeFileSync(filePath, content, 'utf-8');
  return filePath;
}

/**
 * Check if a value needs quoting in a .env file.
 * Quote if it contains spaces, special chars, or is empty.
 */
function needsQuoting(val) {
  if (!val || val.length === 0) return true;
  return /[\s#"'`\\$!]/.test(val);
}

/**
 * Escape double quotes inside a value.
 */
function escapeQuotes(val) {
  return val.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

module.exports = { writeEnvFile };
